PSClubs/Controllers/PSCountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PSClubs.Models;

namespace PSClubs.Controllers
{//This Controller is use to display the country table of the Clubs database with this controller as we are using it with CRUD operation we can manupulate data in the database,it has all four CRUD operation Create delelte update and read
    public class PSCountryController : Controller
    {
        private readonly PSClubsContext _context;
        // this is the constructer of the controller which creates an instance of the controller whenever this controller is called 
        public PSCountryController(PSClubsContext context)
        {
            _context = context;
        }
        //This method is called whenever no action is defined in the search tab of browser it shows list of all countries no inpout value(id) is required for this method to return view
        // GET: PSCountry
        public async Task<IActionResult> Index()
        {
            return View(await _context.Country.ToListAsync());
        }
        //This method is used to show details of the specific country i.e. row from the country table. the id store the unique row number to show
        // GET: PSCountry/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country
                .FirstOrDefaultAsync(m => m.CountryCode == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }
        //This method is use to show create page in website where user can add new entries in the database by creating new row by adding the details in the page called by this method
        // GET: PSCountry/Create
        public IActionResult Create()
        {
            return View();
        }
        //this is a post method which is used to take all the details user added in the create view and store them to database and redirect user to index page where he can see new entries
        // POST: PSCountry/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CountryCode,Name,PostalPattern,PhonePattern,FederalSalesTax,ProvinceTerminology")] Country country)
        {
            if (ModelState.IsValid)
            {
                TempData["Message"] = $"new country '{country.Name}' has been added "; 
                _context.Add(country);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }
        //this is a get method which is callee with specific id which identify which row to edit in the database user can use this method which returns a view from where rows can be edited
        // GET: PSCountry/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country.FindAsync(id);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }
        // this is simply a post method to post all the values user entered in order to manupulate the data in the Clubs database country table. it always have an id
        // POST: PSCountry/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CountryCode,Name,PostalPattern,PhonePattern,FederalSalesTax,ProvinceTerminology")] Country country)
        {
            if (id != country.CountryCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(country);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountryExists(country.CountryCode))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }
        //This is also a get method which is used to delete a row from the database in country table. id is used heree to identify the row that need to be deleted.
        // GET: PSCountry/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country
                .FirstOrDefaultAsync(m => m.CountryCode == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }
        //This is a post method mean the data filled in a form will be posted by this method to server where in delete view it take parameter in id to delete the specific row from country table.
        // POST: PSCountry/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var country = await _context.Country.FindAsync(id);
            _context.Country.Remove(country);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        //this method is called when user tries to enter the country code, as its a prirmary key user cant use more than one country.
        private bool CountryExists(string id)
        {
            return _context.Country.Any(e => e.CountryCode == id);
        }
    }
}

PSClubs/Controllers/PSStyleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PSClubs.Models;

namespace PSClubs.Controllers
{//This is the Style controller which is used to show details of style table from Clubs database by defualt index view is called which show all the styles in the file it also have all CRUD operation like other two controllers(instrumet and country) it uses the clubs connection string
    public class PSStyleController : Controller
    {//this is a constructor used to create a context whenever style controller is intialized 
        private readonly PSClubsContext _context;

        public PSStyleController(PSClubsContext context)
        {
            _context = context;
        }
        //this is a get method use to show all the styles in the database this also called by defualt when no action is mentioned.
        // GET: PSStyle
        public async Task<IActionResult> Index()
        {
            return View(await _context.Style.ToListAsync());
        }
        //This is a get method use to show details of a specfic style user clicked on here id is mandatory as it take the primary key for the row to show details this method is called when detail view is clicked
        // GET: PSStyle/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var style = await _context.Style
                .FirstOrDefaultAsync(m => m.StyleName == id);
            if (style == null)
            {
                return NotFound();
            }

            return View(style);
        }
        //this is a get method simply called when create view is called by user.
        // GET: PSStyle/Create
        public IActionResult Create()
        {
            return View();
        }
        //This is a post method to save user entered details when the submit button was clicked it takes the information and create a new row if everythings gets validated
        // POST: PSStyle/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StyleName,Description")] Style style)
        {
            if (ModelState.IsValid)
            {
                _context.Add(style);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(style);
        }
        //this is a get method which gets the details of the row taht need to be edited and fills it with last save information for user to change it. id here is mandatory as it contains the primary key for the row that need to be changed.
        // GET: PSStyle/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var style = await _context.Style.FindAsync(id);
            if (style == null)
            {
                return NotFound();
            }
            return View(style);
        }
        //This is post method its called when user is in edit view and tries to submit the form, it gets validated and changes are reflected in the database on success, and index is called so user can see changes
        // POST: PSStyle/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("StyleName,Description")] Style style)
        {
            if (id != style.StyleName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(style);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StyleExists(style.StyleName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(style);
        }
        //this is get method to show details of the row that will be deleted as user clicked on the delete link corresponding to a specific row having its primary key stored in ID for this view
        // GET: PSStyle/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var style = await _context.Style
                .FirstOrDefaultAsync(m => m.StyleName == id);
            if (style == null)
            {
                return NotFound();
            }

            return View(style);
        }
        //this is a post method which is used when user confirms the to be deleted row and changes are reflected in the database.
        // POST: PSStyle/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var style = await _context.Style.FindAsync(id);
            _context.Style.Remove(style);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        //this method is used when user tries to put same primary key style name in two rows/ entries
        private bool StyleExists(string id)
        {
            return _context.Style.Any(e => e.StyleName == id);
        }
    }
}

PSClubs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PSClubs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/datatables/css/jquery.dataTables.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PSClubs</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PSCountry" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PSStyle" asp-action="Index">Styles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PSInstrument" asp-action="Index">Instruments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container ">
        @if (TempData["Message"] != null) { 
        <div  class="alert alert-danger" role="alert">@TempData["Message"]</div>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a href="mailto:Psingh2445@conestogac.on.ca?subject=PSClubs">Prabhjot Singh</a> Section1
            <ul class="navbar-navph flex-grow-1" style="float:right; list-style:none">
                <li class="nav-item" style="float:left;">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item" style="float:left; ">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
            </ul>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
    @RenderSection("Scripts", required: false)


    <script type="text/javascript">
        $(document).ready(function(){
            $(".table").DataTable();
        });
    </script>
</body>
</html>